name: Docker Image CI

on:
  push:
    branches: [ azure ]
  pull_request:
    branches: [ azure ]

permissions:
  id-token: write
  contents: read

jobs:

  build:
    environment: dev
    runs-on: ubuntu-latest
    env:
      IMAGE: ${{ vars.app_name }}:${{ github.sha }}
      REPO: ${{ vars.ACR }}.azurecr.io
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login 
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: true

      - name: Login to ACR
        run: | 
          az acr login -n ${{ vars.ACR }}

      - name: build and push
        run: az acr build --registry ${{ env.REPO }} --image ${{ env.image}}

      # - name: Build the Docker image
      #   run: |
      #     docker build . --file Dockerfile --tag ${{ env.REPO }}/${{ env.IMAGE }}

      # - name: Pushes the Docker image
      #   run: |
      #     docker push ${{ env.REPO }}/${{ env.IMAGE }}

      - name: Deploys the webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.APP_NAME }}
          images:  ${{ env.REPO }}/${{ env.IMAGE }}