name: Docker Image CI

on:
  push:
    branches: [ azure ]
  pull_request:
    branches: [ azure ]

jobs:

  build:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login 
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: true

      - name: az cli test
        run: | 
          az group list



      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)